[package]
name = "gitrivia"
version = "0.1.0"
edition = "2018"

[dependencies]
git2 = "0.13"
chrono = "0.4"
clap   = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
